# Generated by Django 3.2.9 on 2021-11-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_auto_20211127_1754"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="game",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to="games.game"
            ),
            preserve_default=False,
        ),
    ]
