# Generated by Django 3.2.9 on 2021-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_players",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="max_players",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
